-- Movie table
CREATE TABLE IF NOT EXISTS movies (
    movie_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    genre TEXT,
    synopsis TEXT,
    director TEXT,
    `comment` TEXT
);

INSERT INTO movies (title, genre, synopsis, director, comment) VALUES 
('The Dark Knight', 'Action', 'Batman faces the Joker to save Gotham City from chaos.', 'Christopher Nolan', 'Masterpiece! Heath Ledger delivers an unforgettable performance as the Joker.'),
('Pulp Fiction', 'Crime', 'The lives of several Los Angeles criminals intertwine unexpectedly.', 'Quentin Tarantino', 'Iconic dialogues, brilliant non-linear storytelling, and a killer soundtrack.'),
('Forrest Gump', 'Drama', 'The story of a simple man witnessing major events in American history.', 'Robert Zemeckis', 'A deeply heartwarming and emotional journey through modern American history.'),
('Matrix', 'Sci-Fi', 'A hacker discovers that his reality is only a computer simulation.', 'Lana Wachowski, Lilly Wachowski', 'Mind-bending sci-fi that completely revolutionized action cinema and special effects.'),
('The Lion King', 'Animation', 'A young lion must reclaim his place as king after his father''s death.', 'Roger Allers, Rob Minkoff', 'The ultimate Disney classic with breathtaking music by Elton John and Hans Zimmer.'),
('Gladiator', 'Action', 'A fallen Roman general seeks revenge against a corrupt emperor.', 'Ridley Scott', 'Epic scale, powerful orchestral score, and an incredible performance by Russell Crowe.'),
('Seven', 'Thriller', 'Two detectives hunt a serial killer inspired by the seven deadly sins.', 'David Fincher', 'Incredibly dark, atmospheric, with one of the most shocking endings in cinema history.'),
('Spirited Away', 'Animation', 'A young girl becomes trapped in a world inhabited by spirits.', 'Hayao Miyazaki', 'A magical, visually stunning, and deeply imaginative masterpiece from Studio Ghibli.'),
('Fight Club', 'Drama', 'An insomniac office worker creates an underground fight club.', 'David Fincher', 'A brilliant, chaotic critique of consumerism with a legendary plot twist.'),
('Django Unchained', 'Western', 'A freed slave joins forces with a bounty hunter to rescue his wife.', 'Quentin Tarantino', 'A bold, violent, and highly entertaining modern take on the Western genre.'),
('The Lord of the Rings', 'Fantasy', 'A hobbit embarks on a quest to destroy an evil ring and save Middle-earth.', 'Peter Jackson', 'The pinnacle of cinematic fantasy. An absolute triumph of filmmaking.'),
('Shutter Island', 'Thriller', 'A marshal investigates the disappearance of a patient in a psychiatric hospital.', 'Martin Scorsese', 'A haunting psychological thriller that keeps you guessing until the very last second.'),
('Your Name', 'Animation', 'Two teenagers mysteriously swap bodies.', 'Makoto Shinkai', 'A visually breathtaking and emotionally powerful story about fate and connection.'),
('The Grand Budapest Hotel', 'Comedy', 'The adventures of a hotel concierge and his protégé.', 'Wes Anderson', 'Charming, quirky, and filled with Wes Anderson''s signature symmetrical visual style.'),
('Gone Girl', 'Thriller', 'A man becomes the prime suspect after his wife disappears.', 'David Fincher', 'A sharp, twisting, and cynical look at modern media and toxic relationships.'),
('Blade Runner 2049', 'Sci-Fi', 'An officer uncovers a long-buried secret.', 'Denis Villeneuve', 'A visually magnificent and deeply philosophical sequel to the cyberpunk classic.'),
('Whiplash', 'Drama', 'A young drummer endures the pressure of a tyrannical teacher.', 'Damien Chazelle', 'An intense, high-octane psychological battle driven by phenomenal jazz music.'),
('Coco', 'Animation', 'A boy explores the world of the dead.', 'Lee Unkrich', 'A beautiful, colorful, and deeply moving celebration of family and Mexican culture.'),
('The Revenant', 'Adventure', 'A trapper struggles to survive in the wilderness.', 'Alejandro G. Iñárritu', 'A brutal yet stunningly shot survival story that finally won DiCaprio his Oscar.'),
('Inglourious Basterds', 'War', 'A group of soldiers carries out violent missions during World War II.', 'Quentin Tarantino', 'An audacious, suspenseful, and dialogue-driven alternate history masterpiece.'),
('The Truman Show', 'Drama', 'A man discovers that his entire life is a television show.', 'Peter Weir', 'A prophetic and brilliant tragicomedy about privacy, media, and human freedom.'),
('Joker', 'Drama', 'The descent of a man into madness.', 'Todd Phillips', 'A gritty, grounded character study anchored by Joaquin Phoenix''s haunting performance.'),
('Mad Max: Fury Road', 'Action', 'A woman rebels in a post-apocalyptic world.', 'George Miller', 'Two hours of absolute, non-stop, masterfully directed action and practical effects.'),
('Alien', 'Horror', 'A crew is hunted by a deadly extraterrestrial creature.', 'Ridley Scott', 'The gold standard of sci-fi horror. Masterful pacing and terrifying atmosphere.'),
('Oldboy', 'Action', 'A man seeks revenge after being imprisoned for 15 years.', 'Park Chan-wook', 'A brutal, poetic, and utterly unforgettable South Korean revenge masterpiece.'),
('Toy Story', 'Animation', 'Toys come to life when humans are not around.', 'John Lasseter', 'The historic masterpiece that started it all for Pixar. Charming and timeless.'),
('The Wolf of Wall Street', 'Biography', 'The rise and fall of a stockbroker.', 'Martin Scorsese', 'A wild, hilarious, and completely chaotic 3-hour ride fueled by pure greed.'),
('Green Book', 'Drama', 'A pianist and his driver travel across America.', 'Peter Farrelly', 'A heartwarming, well-acted feel-good movie about an unlikely friendship.'),
('Arrival', 'Sci-Fi', 'A linguist attempts to communicate with aliens.', 'Denis Villeneuve', 'An incredibly smart, emotional, and unique take on a first-contact alien story.'),
('1917', 'War', 'Two soldiers must deliver a critical message during World War I.', 'Sam Mendes', 'An immersive, technical marvel filmed to look like one continuous shot.');
